[package]
name = "video_01_setup_primitives"
version = "0.1.0"
authors = ["happybearday <45377518+happybearday@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
